name: Sync Domain Lists

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout current repo
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0

    - name: Checkout source repo
      uses: actions/checkout@v4
      with:
        repository: v2fly/domain-list-community
        # This path places the checkout alongside the main repo, not inside it
        path: ../source-repo 

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Convert domain lists
      run: |
        # Adjust the source path to match the new checkout location
        python convert_domains.py ../source-repo/data ./surge-domains

    - name: Commit and push changes
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "Update domain lists ${{ github.run_id }}"
        branch: main
        commit_user_name: GitHub Action
        commit_user_email: action@github.com
        add_options: '-A'
        push_options: '--force-with-lease'
